# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='图片名称')),
                ('image', models.FileField(upload_to='./static/upload', verbose_name='文件')),
            ],
        ),
    ]
