# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_name',
            field=models.CharField(default='', max_length=128, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
    ]
